server:
  port: 80

spring:
  application:
    name: microserviceCloud-consumer-dept-80

eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:      
    instance-id: microserviceCloud-consumer-dept-80    #自定义服务名称
    prefer-ip-address: true #访问路径可以显示IP地址        
    
info: 
  app.name: microserviceCloud-consumer-dept-80
  company.name: www.yangheng.com  
  build.artigactId: ${project.artifactId}$
  build.version:  $project.version$